services:
  # ========================
  # 1. Backend API + Collector
  # ========================
  - type: web
    name: weather-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false   # ให้กรอกใน Render Dashboard
      - key: OPENWEATHER_API_KEY
        sync: false   # ให้กรอกใน Render Dashboard
      - key: PORT
        value: "4000"

  # ========================
  # 2. Frontend (React UI)
  # ========================
  - type: web
    name: weather-frontend
    runtime: docker
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "3000"
      - key: BACKEND_URL
        value: "https://weather-backend.onrender.com"
